//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfTheResearch.AuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AuthLevelList", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch", ItemName="AuthLevel")]
    [System.SerializableAttribute()]
    public class AuthLevelList : System.Collections.Generic.List<wpfTheResearch.AuthService.AuthLevel> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthLevel", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class AuthLevel : wpfTheResearch.AuthService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.AuthService.AuthLevel))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.IAuth")]
    public interface IAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/selectAll", ReplyAction="http://tempuri.org/IAuth/selectAllResponse")]
        wpfTheResearch.AuthService.AuthLevelList selectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/selectAll", ReplyAction="http://tempuri.org/IAuth/selectAllResponse")]
        System.Threading.Tasks.Task<wpfTheResearch.AuthService.AuthLevelList> selectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Add", ReplyAction="http://tempuri.org/IAuth/AddResponse")]
        int Add(wpfTheResearch.AuthService.AuthLevel authLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Add", ReplyAction="http://tempuri.org/IAuth/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(wpfTheResearch.AuthService.AuthLevel authLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/remove", ReplyAction="http://tempuri.org/IAuth/removeResponse")]
        int remove(wpfTheResearch.AuthService.AuthLevel authLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/remove", ReplyAction="http://tempuri.org/IAuth/removeResponse")]
        System.Threading.Tasks.Task<int> removeAsync(wpfTheResearch.AuthService.AuthLevel authLevel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthChannel : wpfTheResearch.AuthService.IAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<wpfTheResearch.AuthService.IAuth>, wpfTheResearch.AuthService.IAuth {
        
        public AuthClient() {
        }
        
        public AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wpfTheResearch.AuthService.AuthLevelList selectAll() {
            return base.Channel.selectAll();
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.AuthService.AuthLevelList> selectAllAsync() {
            return base.Channel.selectAllAsync();
        }
        
        public int Add(wpfTheResearch.AuthService.AuthLevel authLevel) {
            return base.Channel.Add(authLevel);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(wpfTheResearch.AuthService.AuthLevel authLevel) {
            return base.Channel.AddAsync(authLevel);
        }
        
        public int remove(wpfTheResearch.AuthService.AuthLevel authLevel) {
            return base.Channel.remove(authLevel);
        }
        
        public System.Threading.Tasks.Task<int> removeAsync(wpfTheResearch.AuthService.AuthLevel authLevel) {
            return base.Channel.removeAsync(authLevel);
        }
    }
}
