//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfTheResearch.ValidationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidationService.ValidationSoap")]
    public interface ValidationSoap {
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isEmail", ReplyAction="*")]
        wpfTheResearch.ValidationService.isEmailResponse isEmail(wpfTheResearch.ValidationService.isEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isEmailResponse> isEmailAsync(wpfTheResearch.ValidationService.isEmailRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isFrancePhoneNumber", ReplyAction="*")]
        wpfTheResearch.ValidationService.isFrancePhoneNumberResponse isFrancePhoneNumber(wpfTheResearch.ValidationService.isFrancePhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isFrancePhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isFrancePhoneNumberResponse> isFrancePhoneNumberAsync(wpfTheResearch.ValidationService.isFrancePhoneNumberRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGermanPhoneNumber", ReplyAction="*")]
        wpfTheResearch.ValidationService.isGermanPhoneNumberResponse isGermanPhoneNumber(wpfTheResearch.ValidationService.isGermanPhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGermanPhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isGermanPhoneNumberResponse> isGermanPhoneNumberAsync(wpfTheResearch.ValidationService.isGermanPhoneNumberRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUSPhoneNumber", ReplyAction="*")]
        wpfTheResearch.ValidationService.isUSPhoneNumberResponse isUSPhoneNumber(wpfTheResearch.ValidationService.isUSPhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUSPhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isUSPhoneNumberResponse> isUSPhoneNumberAsync(wpfTheResearch.ValidationService.isUSPhoneNumberRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isIp", ReplyAction="*")]
        wpfTheResearch.ValidationService.isIpResponse isIp(wpfTheResearch.ValidationService.isIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isIp", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isIpResponse> isIpAsync(wpfTheResearch.ValidationService.isIpRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isISBN", ReplyAction="*")]
        wpfTheResearch.ValidationService.isISBNResponse isISBN(wpfTheResearch.ValidationService.isISBNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isISBN", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isISBNResponse> isISBNAsync(wpfTheResearch.ValidationService.isISBNRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGUID", ReplyAction="*")]
        wpfTheResearch.ValidationService.isGUIDResponse isGUID(wpfTheResearch.ValidationService.isGUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGUID", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isGUIDResponse> isGUIDAsync(wpfTheResearch.ValidationService.isGUIDRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isURL", ReplyAction="*")]
        wpfTheResearch.ValidationService.isURLResponse isURL(wpfTheResearch.ValidationService.isURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isURL", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isURLResponse> isURLAsync(wpfTheResearch.ValidationService.isURLRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/is5Numbers", ReplyAction="*")]
        wpfTheResearch.ValidationService.is5NumbersResponse is5Numbers(wpfTheResearch.ValidationService.is5NumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/is5Numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.is5NumbersResponse> is5NumbersAsync(wpfTheResearch.ValidationService.is5NumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isEmail", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isEmailRequestBody Body;
        
        public isEmailRequest() {
        }
        
        public isEmailRequest(wpfTheResearch.ValidationService.isEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isEmailRequestBody() {
        }
        
        public isEmailRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isEmailResponseBody Body;
        
        public isEmailResponse() {
        }
        
        public isEmailResponse(wpfTheResearch.ValidationService.isEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isEmailResult;
        
        public isEmailResponseBody() {
        }
        
        public isEmailResponseBody(bool isEmailResult) {
            this.isEmailResult = isEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isFrancePhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isFrancePhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isFrancePhoneNumberRequestBody Body;
        
        public isFrancePhoneNumberRequest() {
        }
        
        public isFrancePhoneNumberRequest(wpfTheResearch.ValidationService.isFrancePhoneNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isFrancePhoneNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isFrancePhoneNumberRequestBody() {
        }
        
        public isFrancePhoneNumberRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isFrancePhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isFrancePhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isFrancePhoneNumberResponseBody Body;
        
        public isFrancePhoneNumberResponse() {
        }
        
        public isFrancePhoneNumberResponse(wpfTheResearch.ValidationService.isFrancePhoneNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isFrancePhoneNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isFrancePhoneNumberResult;
        
        public isFrancePhoneNumberResponseBody() {
        }
        
        public isFrancePhoneNumberResponseBody(bool isFrancePhoneNumberResult) {
            this.isFrancePhoneNumberResult = isFrancePhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGermanPhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGermanPhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isGermanPhoneNumberRequestBody Body;
        
        public isGermanPhoneNumberRequest() {
        }
        
        public isGermanPhoneNumberRequest(wpfTheResearch.ValidationService.isGermanPhoneNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGermanPhoneNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isGermanPhoneNumberRequestBody() {
        }
        
        public isGermanPhoneNumberRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGermanPhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGermanPhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isGermanPhoneNumberResponseBody Body;
        
        public isGermanPhoneNumberResponse() {
        }
        
        public isGermanPhoneNumberResponse(wpfTheResearch.ValidationService.isGermanPhoneNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGermanPhoneNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isGermanPhoneNumberResult;
        
        public isGermanPhoneNumberResponseBody() {
        }
        
        public isGermanPhoneNumberResponseBody(bool isGermanPhoneNumberResult) {
            this.isGermanPhoneNumberResult = isGermanPhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isUSPhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isUSPhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isUSPhoneNumberRequestBody Body;
        
        public isUSPhoneNumberRequest() {
        }
        
        public isUSPhoneNumberRequest(wpfTheResearch.ValidationService.isUSPhoneNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isUSPhoneNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isUSPhoneNumberRequestBody() {
        }
        
        public isUSPhoneNumberRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isUSPhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isUSPhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isUSPhoneNumberResponseBody Body;
        
        public isUSPhoneNumberResponse() {
        }
        
        public isUSPhoneNumberResponse(wpfTheResearch.ValidationService.isUSPhoneNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isUSPhoneNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isUSPhoneNumberResult;
        
        public isUSPhoneNumberResponseBody() {
        }
        
        public isUSPhoneNumberResponseBody(bool isUSPhoneNumberResult) {
            this.isUSPhoneNumberResult = isUSPhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isIpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isIp", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isIpRequestBody Body;
        
        public isIpRequest() {
        }
        
        public isIpRequest(wpfTheResearch.ValidationService.isIpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isIpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isIpRequestBody() {
        }
        
        public isIpRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isIpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isIpResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isIpResponseBody Body;
        
        public isIpResponse() {
        }
        
        public isIpResponse(wpfTheResearch.ValidationService.isIpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isIpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isIpResult;
        
        public isIpResponseBody() {
        }
        
        public isIpResponseBody(bool isIpResult) {
            this.isIpResult = isIpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isISBN", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isISBNRequestBody Body;
        
        public isISBNRequest() {
        }
        
        public isISBNRequest(wpfTheResearch.ValidationService.isISBNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isISBNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isISBNRequestBody() {
        }
        
        public isISBNRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isISBNResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isISBNResponseBody Body;
        
        public isISBNResponse() {
        }
        
        public isISBNResponse(wpfTheResearch.ValidationService.isISBNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isISBNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isISBNResult;
        
        public isISBNResponseBody() {
        }
        
        public isISBNResponseBody(bool isISBNResult) {
            this.isISBNResult = isISBNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGUID", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isGUIDRequestBody Body;
        
        public isGUIDRequest() {
        }
        
        public isGUIDRequest(wpfTheResearch.ValidationService.isGUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isGUIDRequestBody() {
        }
        
        public isGUIDRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGUIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isGUIDResponseBody Body;
        
        public isGUIDResponse() {
        }
        
        public isGUIDResponse(wpfTheResearch.ValidationService.isGUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isGUIDResult;
        
        public isGUIDResponseBody() {
        }
        
        public isGUIDResponseBody(bool isGUIDResult) {
            this.isGUIDResult = isGUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isURL", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isURLRequestBody Body;
        
        public isURLRequest() {
        }
        
        public isURLRequest(wpfTheResearch.ValidationService.isURLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isURLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isURLRequestBody() {
        }
        
        public isURLRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isURLResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.isURLResponseBody Body;
        
        public isURLResponse() {
        }
        
        public isURLResponse(wpfTheResearch.ValidationService.isURLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isURLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isURLResult;
        
        public isURLResponseBody() {
        }
        
        public isURLResponseBody(bool isURLResult) {
            this.isURLResult = isURLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class is5NumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="is5Numbers", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.is5NumbersRequestBody Body;
        
        public is5NumbersRequest() {
        }
        
        public is5NumbersRequest(wpfTheResearch.ValidationService.is5NumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class is5NumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public is5NumbersRequestBody() {
        }
        
        public is5NumbersRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class is5NumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="is5NumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public wpfTheResearch.ValidationService.is5NumbersResponseBody Body;
        
        public is5NumbersResponse() {
        }
        
        public is5NumbersResponse(wpfTheResearch.ValidationService.is5NumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class is5NumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool is5NumbersResult;
        
        public is5NumbersResponseBody() {
        }
        
        public is5NumbersResponseBody(bool is5NumbersResult) {
            this.is5NumbersResult = is5NumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidationSoapChannel : wpfTheResearch.ValidationService.ValidationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidationSoapClient : System.ServiceModel.ClientBase<wpfTheResearch.ValidationService.ValidationSoap>, wpfTheResearch.ValidationService.ValidationSoap {
        
        public ValidationSoapClient() {
        }
        
        public ValidationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.isEmailResponse wpfTheResearch.ValidationService.ValidationSoap.isEmail(wpfTheResearch.ValidationService.isEmailRequest request) {
            return base.Channel.isEmail(request);
        }
        
        public bool isEmail(string str) {
            wpfTheResearch.ValidationService.isEmailRequest inValue = new wpfTheResearch.ValidationService.isEmailRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isEmailRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.isEmailResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isEmail(inValue);
            return retVal.Body.isEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isEmailResponse> wpfTheResearch.ValidationService.ValidationSoap.isEmailAsync(wpfTheResearch.ValidationService.isEmailRequest request) {
            return base.Channel.isEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isEmailResponse> isEmailAsync(string str) {
            wpfTheResearch.ValidationService.isEmailRequest inValue = new wpfTheResearch.ValidationService.isEmailRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isEmailRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.isFrancePhoneNumberResponse wpfTheResearch.ValidationService.ValidationSoap.isFrancePhoneNumber(wpfTheResearch.ValidationService.isFrancePhoneNumberRequest request) {
            return base.Channel.isFrancePhoneNumber(request);
        }
        
        public bool isFrancePhoneNumber(string str) {
            wpfTheResearch.ValidationService.isFrancePhoneNumberRequest inValue = new wpfTheResearch.ValidationService.isFrancePhoneNumberRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isFrancePhoneNumberRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.isFrancePhoneNumberResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isFrancePhoneNumber(inValue);
            return retVal.Body.isFrancePhoneNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isFrancePhoneNumberResponse> wpfTheResearch.ValidationService.ValidationSoap.isFrancePhoneNumberAsync(wpfTheResearch.ValidationService.isFrancePhoneNumberRequest request) {
            return base.Channel.isFrancePhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isFrancePhoneNumberResponse> isFrancePhoneNumberAsync(string str) {
            wpfTheResearch.ValidationService.isFrancePhoneNumberRequest inValue = new wpfTheResearch.ValidationService.isFrancePhoneNumberRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isFrancePhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isFrancePhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.isGermanPhoneNumberResponse wpfTheResearch.ValidationService.ValidationSoap.isGermanPhoneNumber(wpfTheResearch.ValidationService.isGermanPhoneNumberRequest request) {
            return base.Channel.isGermanPhoneNumber(request);
        }
        
        public bool isGermanPhoneNumber(string str) {
            wpfTheResearch.ValidationService.isGermanPhoneNumberRequest inValue = new wpfTheResearch.ValidationService.isGermanPhoneNumberRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isGermanPhoneNumberRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.isGermanPhoneNumberResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isGermanPhoneNumber(inValue);
            return retVal.Body.isGermanPhoneNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isGermanPhoneNumberResponse> wpfTheResearch.ValidationService.ValidationSoap.isGermanPhoneNumberAsync(wpfTheResearch.ValidationService.isGermanPhoneNumberRequest request) {
            return base.Channel.isGermanPhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isGermanPhoneNumberResponse> isGermanPhoneNumberAsync(string str) {
            wpfTheResearch.ValidationService.isGermanPhoneNumberRequest inValue = new wpfTheResearch.ValidationService.isGermanPhoneNumberRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isGermanPhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isGermanPhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.isUSPhoneNumberResponse wpfTheResearch.ValidationService.ValidationSoap.isUSPhoneNumber(wpfTheResearch.ValidationService.isUSPhoneNumberRequest request) {
            return base.Channel.isUSPhoneNumber(request);
        }
        
        public bool isUSPhoneNumber(string str) {
            wpfTheResearch.ValidationService.isUSPhoneNumberRequest inValue = new wpfTheResearch.ValidationService.isUSPhoneNumberRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isUSPhoneNumberRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.isUSPhoneNumberResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isUSPhoneNumber(inValue);
            return retVal.Body.isUSPhoneNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isUSPhoneNumberResponse> wpfTheResearch.ValidationService.ValidationSoap.isUSPhoneNumberAsync(wpfTheResearch.ValidationService.isUSPhoneNumberRequest request) {
            return base.Channel.isUSPhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isUSPhoneNumberResponse> isUSPhoneNumberAsync(string str) {
            wpfTheResearch.ValidationService.isUSPhoneNumberRequest inValue = new wpfTheResearch.ValidationService.isUSPhoneNumberRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isUSPhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isUSPhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.isIpResponse wpfTheResearch.ValidationService.ValidationSoap.isIp(wpfTheResearch.ValidationService.isIpRequest request) {
            return base.Channel.isIp(request);
        }
        
        public bool isIp(string str) {
            wpfTheResearch.ValidationService.isIpRequest inValue = new wpfTheResearch.ValidationService.isIpRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isIpRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.isIpResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isIp(inValue);
            return retVal.Body.isIpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isIpResponse> wpfTheResearch.ValidationService.ValidationSoap.isIpAsync(wpfTheResearch.ValidationService.isIpRequest request) {
            return base.Channel.isIpAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isIpResponse> isIpAsync(string str) {
            wpfTheResearch.ValidationService.isIpRequest inValue = new wpfTheResearch.ValidationService.isIpRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isIpRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isIpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.isISBNResponse wpfTheResearch.ValidationService.ValidationSoap.isISBN(wpfTheResearch.ValidationService.isISBNRequest request) {
            return base.Channel.isISBN(request);
        }
        
        public bool isISBN(string str) {
            wpfTheResearch.ValidationService.isISBNRequest inValue = new wpfTheResearch.ValidationService.isISBNRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isISBNRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.isISBNResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isISBN(inValue);
            return retVal.Body.isISBNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isISBNResponse> wpfTheResearch.ValidationService.ValidationSoap.isISBNAsync(wpfTheResearch.ValidationService.isISBNRequest request) {
            return base.Channel.isISBNAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isISBNResponse> isISBNAsync(string str) {
            wpfTheResearch.ValidationService.isISBNRequest inValue = new wpfTheResearch.ValidationService.isISBNRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isISBNRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isISBNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.isGUIDResponse wpfTheResearch.ValidationService.ValidationSoap.isGUID(wpfTheResearch.ValidationService.isGUIDRequest request) {
            return base.Channel.isGUID(request);
        }
        
        public bool isGUID(string str) {
            wpfTheResearch.ValidationService.isGUIDRequest inValue = new wpfTheResearch.ValidationService.isGUIDRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isGUIDRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.isGUIDResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isGUID(inValue);
            return retVal.Body.isGUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isGUIDResponse> wpfTheResearch.ValidationService.ValidationSoap.isGUIDAsync(wpfTheResearch.ValidationService.isGUIDRequest request) {
            return base.Channel.isGUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isGUIDResponse> isGUIDAsync(string str) {
            wpfTheResearch.ValidationService.isGUIDRequest inValue = new wpfTheResearch.ValidationService.isGUIDRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isGUIDRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isGUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.isURLResponse wpfTheResearch.ValidationService.ValidationSoap.isURL(wpfTheResearch.ValidationService.isURLRequest request) {
            return base.Channel.isURL(request);
        }
        
        public bool isURL(string str) {
            wpfTheResearch.ValidationService.isURLRequest inValue = new wpfTheResearch.ValidationService.isURLRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isURLRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.isURLResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isURL(inValue);
            return retVal.Body.isURLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isURLResponse> wpfTheResearch.ValidationService.ValidationSoap.isURLAsync(wpfTheResearch.ValidationService.isURLRequest request) {
            return base.Channel.isURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.isURLResponse> isURLAsync(string str) {
            wpfTheResearch.ValidationService.isURLRequest inValue = new wpfTheResearch.ValidationService.isURLRequest();
            inValue.Body = new wpfTheResearch.ValidationService.isURLRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).isURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wpfTheResearch.ValidationService.is5NumbersResponse wpfTheResearch.ValidationService.ValidationSoap.is5Numbers(wpfTheResearch.ValidationService.is5NumbersRequest request) {
            return base.Channel.is5Numbers(request);
        }
        
        public bool is5Numbers(string str) {
            wpfTheResearch.ValidationService.is5NumbersRequest inValue = new wpfTheResearch.ValidationService.is5NumbersRequest();
            inValue.Body = new wpfTheResearch.ValidationService.is5NumbersRequestBody();
            inValue.Body.str = str;
            wpfTheResearch.ValidationService.is5NumbersResponse retVal = ((wpfTheResearch.ValidationService.ValidationSoap)(this)).is5Numbers(inValue);
            return retVal.Body.is5NumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wpfTheResearch.ValidationService.is5NumbersResponse> wpfTheResearch.ValidationService.ValidationSoap.is5NumbersAsync(wpfTheResearch.ValidationService.is5NumbersRequest request) {
            return base.Channel.is5NumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.ValidationService.is5NumbersResponse> is5NumbersAsync(string str) {
            wpfTheResearch.ValidationService.is5NumbersRequest inValue = new wpfTheResearch.ValidationService.is5NumbersRequest();
            inValue.Body = new wpfTheResearch.ValidationService.is5NumbersRequestBody();
            inValue.Body.str = str;
            return ((wpfTheResearch.ValidationService.ValidationSoap)(this)).is5NumbersAsync(inValue);
        }
    }
}
