//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theResearchSite.CategoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CategoryList", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch", ItemName="Category")]
    [System.SerializableAttribute()]
    public class CategoryList : System.Collections.Generic.List<theResearchSite.CategoryService.Category> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class Category : theResearchSite.CategoryService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(theResearchSite.CategoryService.Category))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoryService.ICategories")]
    public interface ICategories {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/selectAll", ReplyAction="http://tempuri.org/ICategories/selectAllResponse")]
        theResearchSite.CategoryService.CategoryList selectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/selectAll", ReplyAction="http://tempuri.org/ICategories/selectAllResponse")]
        System.Threading.Tasks.Task<theResearchSite.CategoryService.CategoryList> selectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Add", ReplyAction="http://tempuri.org/ICategories/AddResponse")]
        int Add(theResearchSite.CategoryService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Add", ReplyAction="http://tempuri.org/ICategories/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(theResearchSite.CategoryService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Remove", ReplyAction="http://tempuri.org/ICategories/RemoveResponse")]
        int Remove(theResearchSite.CategoryService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategories/Remove", ReplyAction="http://tempuri.org/ICategories/RemoveResponse")]
        System.Threading.Tasks.Task<int> RemoveAsync(theResearchSite.CategoryService.Category category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriesChannel : theResearchSite.CategoryService.ICategories, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriesClient : System.ServiceModel.ClientBase<theResearchSite.CategoryService.ICategories>, theResearchSite.CategoryService.ICategories {
        
        public CategoriesClient() {
        }
        
        public CategoriesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public theResearchSite.CategoryService.CategoryList selectAll() {
            return base.Channel.selectAll();
        }
        
        public System.Threading.Tasks.Task<theResearchSite.CategoryService.CategoryList> selectAllAsync() {
            return base.Channel.selectAllAsync();
        }
        
        public int Add(theResearchSite.CategoryService.Category category) {
            return base.Channel.Add(category);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(theResearchSite.CategoryService.Category category) {
            return base.Channel.AddAsync(category);
        }
        
        public int Remove(theResearchSite.CategoryService.Category category) {
            return base.Channel.Remove(category);
        }
        
        public System.Threading.Tasks.Task<int> RemoveAsync(theResearchSite.CategoryService.Category category) {
            return base.Channel.RemoveAsync(category);
        }
    }
}
