//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theResearchSite.ValidationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidationService.ValidationSoap")]
    public interface ValidationSoap {
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isEmail", ReplyAction="*")]
        theResearchSite.ValidationService.isEmailResponse isEmail(theResearchSite.ValidationService.isEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isEmailResponse> isEmailAsync(theResearchSite.ValidationService.isEmailRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isFrancePhoneNumber", ReplyAction="*")]
        theResearchSite.ValidationService.isFrancePhoneNumberResponse isFrancePhoneNumber(theResearchSite.ValidationService.isFrancePhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isFrancePhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isFrancePhoneNumberResponse> isFrancePhoneNumberAsync(theResearchSite.ValidationService.isFrancePhoneNumberRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGermanPhoneNumber", ReplyAction="*")]
        theResearchSite.ValidationService.isGermanPhoneNumberResponse isGermanPhoneNumber(theResearchSite.ValidationService.isGermanPhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGermanPhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isGermanPhoneNumberResponse> isGermanPhoneNumberAsync(theResearchSite.ValidationService.isGermanPhoneNumberRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUSPhoneNumber", ReplyAction="*")]
        theResearchSite.ValidationService.isUSPhoneNumberResponse isUSPhoneNumber(theResearchSite.ValidationService.isUSPhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isUSPhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isUSPhoneNumberResponse> isUSPhoneNumberAsync(theResearchSite.ValidationService.isUSPhoneNumberRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isIp", ReplyAction="*")]
        theResearchSite.ValidationService.isIpResponse isIp(theResearchSite.ValidationService.isIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isIp", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isIpResponse> isIpAsync(theResearchSite.ValidationService.isIpRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isISBN", ReplyAction="*")]
        theResearchSite.ValidationService.isISBNResponse isISBN(theResearchSite.ValidationService.isISBNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isISBN", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isISBNResponse> isISBNAsync(theResearchSite.ValidationService.isISBNRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGUID", ReplyAction="*")]
        theResearchSite.ValidationService.isGUIDResponse isGUID(theResearchSite.ValidationService.isGUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isGUID", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isGUIDResponse> isGUIDAsync(theResearchSite.ValidationService.isGUIDRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isURL", ReplyAction="*")]
        theResearchSite.ValidationService.isURLResponse isURL(theResearchSite.ValidationService.isURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isURL", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isURLResponse> isURLAsync(theResearchSite.ValidationService.isURLRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/is5Numbers", ReplyAction="*")]
        theResearchSite.ValidationService.is5NumbersResponse is5Numbers(theResearchSite.ValidationService.is5NumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/is5Numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.is5NumbersResponse> is5NumbersAsync(theResearchSite.ValidationService.is5NumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isEmail", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isEmailRequestBody Body;
        
        public isEmailRequest() {
        }
        
        public isEmailRequest(theResearchSite.ValidationService.isEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isEmailRequestBody() {
        }
        
        public isEmailRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isEmailResponseBody Body;
        
        public isEmailResponse() {
        }
        
        public isEmailResponse(theResearchSite.ValidationService.isEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isEmailResult;
        
        public isEmailResponseBody() {
        }
        
        public isEmailResponseBody(bool isEmailResult) {
            this.isEmailResult = isEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isFrancePhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isFrancePhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isFrancePhoneNumberRequestBody Body;
        
        public isFrancePhoneNumberRequest() {
        }
        
        public isFrancePhoneNumberRequest(theResearchSite.ValidationService.isFrancePhoneNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isFrancePhoneNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isFrancePhoneNumberRequestBody() {
        }
        
        public isFrancePhoneNumberRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isFrancePhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isFrancePhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isFrancePhoneNumberResponseBody Body;
        
        public isFrancePhoneNumberResponse() {
        }
        
        public isFrancePhoneNumberResponse(theResearchSite.ValidationService.isFrancePhoneNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isFrancePhoneNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isFrancePhoneNumberResult;
        
        public isFrancePhoneNumberResponseBody() {
        }
        
        public isFrancePhoneNumberResponseBody(bool isFrancePhoneNumberResult) {
            this.isFrancePhoneNumberResult = isFrancePhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGermanPhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGermanPhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isGermanPhoneNumberRequestBody Body;
        
        public isGermanPhoneNumberRequest() {
        }
        
        public isGermanPhoneNumberRequest(theResearchSite.ValidationService.isGermanPhoneNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGermanPhoneNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isGermanPhoneNumberRequestBody() {
        }
        
        public isGermanPhoneNumberRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGermanPhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGermanPhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isGermanPhoneNumberResponseBody Body;
        
        public isGermanPhoneNumberResponse() {
        }
        
        public isGermanPhoneNumberResponse(theResearchSite.ValidationService.isGermanPhoneNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGermanPhoneNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isGermanPhoneNumberResult;
        
        public isGermanPhoneNumberResponseBody() {
        }
        
        public isGermanPhoneNumberResponseBody(bool isGermanPhoneNumberResult) {
            this.isGermanPhoneNumberResult = isGermanPhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isUSPhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isUSPhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isUSPhoneNumberRequestBody Body;
        
        public isUSPhoneNumberRequest() {
        }
        
        public isUSPhoneNumberRequest(theResearchSite.ValidationService.isUSPhoneNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isUSPhoneNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isUSPhoneNumberRequestBody() {
        }
        
        public isUSPhoneNumberRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isUSPhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isUSPhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isUSPhoneNumberResponseBody Body;
        
        public isUSPhoneNumberResponse() {
        }
        
        public isUSPhoneNumberResponse(theResearchSite.ValidationService.isUSPhoneNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isUSPhoneNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isUSPhoneNumberResult;
        
        public isUSPhoneNumberResponseBody() {
        }
        
        public isUSPhoneNumberResponseBody(bool isUSPhoneNumberResult) {
            this.isUSPhoneNumberResult = isUSPhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isIpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isIp", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isIpRequestBody Body;
        
        public isIpRequest() {
        }
        
        public isIpRequest(theResearchSite.ValidationService.isIpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isIpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isIpRequestBody() {
        }
        
        public isIpRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isIpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isIpResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isIpResponseBody Body;
        
        public isIpResponse() {
        }
        
        public isIpResponse(theResearchSite.ValidationService.isIpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isIpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isIpResult;
        
        public isIpResponseBody() {
        }
        
        public isIpResponseBody(bool isIpResult) {
            this.isIpResult = isIpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isISBN", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isISBNRequestBody Body;
        
        public isISBNRequest() {
        }
        
        public isISBNRequest(theResearchSite.ValidationService.isISBNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isISBNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isISBNRequestBody() {
        }
        
        public isISBNRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isISBNResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isISBNResponseBody Body;
        
        public isISBNResponse() {
        }
        
        public isISBNResponse(theResearchSite.ValidationService.isISBNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isISBNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isISBNResult;
        
        public isISBNResponseBody() {
        }
        
        public isISBNResponseBody(bool isISBNResult) {
            this.isISBNResult = isISBNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGUID", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isGUIDRequestBody Body;
        
        public isGUIDRequest() {
        }
        
        public isGUIDRequest(theResearchSite.ValidationService.isGUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isGUIDRequestBody() {
        }
        
        public isGUIDRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isGUIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isGUIDResponseBody Body;
        
        public isGUIDResponse() {
        }
        
        public isGUIDResponse(theResearchSite.ValidationService.isGUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isGUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isGUIDResult;
        
        public isGUIDResponseBody() {
        }
        
        public isGUIDResponseBody(bool isGUIDResult) {
            this.isGUIDResult = isGUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isURL", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isURLRequestBody Body;
        
        public isURLRequest() {
        }
        
        public isURLRequest(theResearchSite.ValidationService.isURLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isURLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public isURLRequestBody() {
        }
        
        public isURLRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isURLResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.isURLResponseBody Body;
        
        public isURLResponse() {
        }
        
        public isURLResponse(theResearchSite.ValidationService.isURLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isURLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isURLResult;
        
        public isURLResponseBody() {
        }
        
        public isURLResponseBody(bool isURLResult) {
            this.isURLResult = isURLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class is5NumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="is5Numbers", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.is5NumbersRequestBody Body;
        
        public is5NumbersRequest() {
        }
        
        public is5NumbersRequest(theResearchSite.ValidationService.is5NumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class is5NumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public is5NumbersRequestBody() {
        }
        
        public is5NumbersRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class is5NumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="is5NumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.ValidationService.is5NumbersResponseBody Body;
        
        public is5NumbersResponse() {
        }
        
        public is5NumbersResponse(theResearchSite.ValidationService.is5NumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class is5NumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool is5NumbersResult;
        
        public is5NumbersResponseBody() {
        }
        
        public is5NumbersResponseBody(bool is5NumbersResult) {
            this.is5NumbersResult = is5NumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidationSoapChannel : theResearchSite.ValidationService.ValidationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidationSoapClient : System.ServiceModel.ClientBase<theResearchSite.ValidationService.ValidationSoap>, theResearchSite.ValidationService.ValidationSoap {
        
        public ValidationSoapClient() {
        }
        
        public ValidationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.isEmailResponse theResearchSite.ValidationService.ValidationSoap.isEmail(theResearchSite.ValidationService.isEmailRequest request) {
            return base.Channel.isEmail(request);
        }
        
        public bool isEmail(string str) {
            theResearchSite.ValidationService.isEmailRequest inValue = new theResearchSite.ValidationService.isEmailRequest();
            inValue.Body = new theResearchSite.ValidationService.isEmailRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.isEmailResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).isEmail(inValue);
            return retVal.Body.isEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isEmailResponse> theResearchSite.ValidationService.ValidationSoap.isEmailAsync(theResearchSite.ValidationService.isEmailRequest request) {
            return base.Channel.isEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.isEmailResponse> isEmailAsync(string str) {
            theResearchSite.ValidationService.isEmailRequest inValue = new theResearchSite.ValidationService.isEmailRequest();
            inValue.Body = new theResearchSite.ValidationService.isEmailRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).isEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.isFrancePhoneNumberResponse theResearchSite.ValidationService.ValidationSoap.isFrancePhoneNumber(theResearchSite.ValidationService.isFrancePhoneNumberRequest request) {
            return base.Channel.isFrancePhoneNumber(request);
        }
        
        public bool isFrancePhoneNumber(string str) {
            theResearchSite.ValidationService.isFrancePhoneNumberRequest inValue = new theResearchSite.ValidationService.isFrancePhoneNumberRequest();
            inValue.Body = new theResearchSite.ValidationService.isFrancePhoneNumberRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.isFrancePhoneNumberResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).isFrancePhoneNumber(inValue);
            return retVal.Body.isFrancePhoneNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isFrancePhoneNumberResponse> theResearchSite.ValidationService.ValidationSoap.isFrancePhoneNumberAsync(theResearchSite.ValidationService.isFrancePhoneNumberRequest request) {
            return base.Channel.isFrancePhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.isFrancePhoneNumberResponse> isFrancePhoneNumberAsync(string str) {
            theResearchSite.ValidationService.isFrancePhoneNumberRequest inValue = new theResearchSite.ValidationService.isFrancePhoneNumberRequest();
            inValue.Body = new theResearchSite.ValidationService.isFrancePhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).isFrancePhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.isGermanPhoneNumberResponse theResearchSite.ValidationService.ValidationSoap.isGermanPhoneNumber(theResearchSite.ValidationService.isGermanPhoneNumberRequest request) {
            return base.Channel.isGermanPhoneNumber(request);
        }
        
        public bool isGermanPhoneNumber(string str) {
            theResearchSite.ValidationService.isGermanPhoneNumberRequest inValue = new theResearchSite.ValidationService.isGermanPhoneNumberRequest();
            inValue.Body = new theResearchSite.ValidationService.isGermanPhoneNumberRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.isGermanPhoneNumberResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).isGermanPhoneNumber(inValue);
            return retVal.Body.isGermanPhoneNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isGermanPhoneNumberResponse> theResearchSite.ValidationService.ValidationSoap.isGermanPhoneNumberAsync(theResearchSite.ValidationService.isGermanPhoneNumberRequest request) {
            return base.Channel.isGermanPhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.isGermanPhoneNumberResponse> isGermanPhoneNumberAsync(string str) {
            theResearchSite.ValidationService.isGermanPhoneNumberRequest inValue = new theResearchSite.ValidationService.isGermanPhoneNumberRequest();
            inValue.Body = new theResearchSite.ValidationService.isGermanPhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).isGermanPhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.isUSPhoneNumberResponse theResearchSite.ValidationService.ValidationSoap.isUSPhoneNumber(theResearchSite.ValidationService.isUSPhoneNumberRequest request) {
            return base.Channel.isUSPhoneNumber(request);
        }
        
        public bool isUSPhoneNumber(string str) {
            theResearchSite.ValidationService.isUSPhoneNumberRequest inValue = new theResearchSite.ValidationService.isUSPhoneNumberRequest();
            inValue.Body = new theResearchSite.ValidationService.isUSPhoneNumberRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.isUSPhoneNumberResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).isUSPhoneNumber(inValue);
            return retVal.Body.isUSPhoneNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isUSPhoneNumberResponse> theResearchSite.ValidationService.ValidationSoap.isUSPhoneNumberAsync(theResearchSite.ValidationService.isUSPhoneNumberRequest request) {
            return base.Channel.isUSPhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.isUSPhoneNumberResponse> isUSPhoneNumberAsync(string str) {
            theResearchSite.ValidationService.isUSPhoneNumberRequest inValue = new theResearchSite.ValidationService.isUSPhoneNumberRequest();
            inValue.Body = new theResearchSite.ValidationService.isUSPhoneNumberRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).isUSPhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.isIpResponse theResearchSite.ValidationService.ValidationSoap.isIp(theResearchSite.ValidationService.isIpRequest request) {
            return base.Channel.isIp(request);
        }
        
        public bool isIp(string str) {
            theResearchSite.ValidationService.isIpRequest inValue = new theResearchSite.ValidationService.isIpRequest();
            inValue.Body = new theResearchSite.ValidationService.isIpRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.isIpResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).isIp(inValue);
            return retVal.Body.isIpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isIpResponse> theResearchSite.ValidationService.ValidationSoap.isIpAsync(theResearchSite.ValidationService.isIpRequest request) {
            return base.Channel.isIpAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.isIpResponse> isIpAsync(string str) {
            theResearchSite.ValidationService.isIpRequest inValue = new theResearchSite.ValidationService.isIpRequest();
            inValue.Body = new theResearchSite.ValidationService.isIpRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).isIpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.isISBNResponse theResearchSite.ValidationService.ValidationSoap.isISBN(theResearchSite.ValidationService.isISBNRequest request) {
            return base.Channel.isISBN(request);
        }
        
        public bool isISBN(string str) {
            theResearchSite.ValidationService.isISBNRequest inValue = new theResearchSite.ValidationService.isISBNRequest();
            inValue.Body = new theResearchSite.ValidationService.isISBNRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.isISBNResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).isISBN(inValue);
            return retVal.Body.isISBNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isISBNResponse> theResearchSite.ValidationService.ValidationSoap.isISBNAsync(theResearchSite.ValidationService.isISBNRequest request) {
            return base.Channel.isISBNAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.isISBNResponse> isISBNAsync(string str) {
            theResearchSite.ValidationService.isISBNRequest inValue = new theResearchSite.ValidationService.isISBNRequest();
            inValue.Body = new theResearchSite.ValidationService.isISBNRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).isISBNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.isGUIDResponse theResearchSite.ValidationService.ValidationSoap.isGUID(theResearchSite.ValidationService.isGUIDRequest request) {
            return base.Channel.isGUID(request);
        }
        
        public bool isGUID(string str) {
            theResearchSite.ValidationService.isGUIDRequest inValue = new theResearchSite.ValidationService.isGUIDRequest();
            inValue.Body = new theResearchSite.ValidationService.isGUIDRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.isGUIDResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).isGUID(inValue);
            return retVal.Body.isGUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isGUIDResponse> theResearchSite.ValidationService.ValidationSoap.isGUIDAsync(theResearchSite.ValidationService.isGUIDRequest request) {
            return base.Channel.isGUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.isGUIDResponse> isGUIDAsync(string str) {
            theResearchSite.ValidationService.isGUIDRequest inValue = new theResearchSite.ValidationService.isGUIDRequest();
            inValue.Body = new theResearchSite.ValidationService.isGUIDRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).isGUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.isURLResponse theResearchSite.ValidationService.ValidationSoap.isURL(theResearchSite.ValidationService.isURLRequest request) {
            return base.Channel.isURL(request);
        }
        
        public bool isURL(string str) {
            theResearchSite.ValidationService.isURLRequest inValue = new theResearchSite.ValidationService.isURLRequest();
            inValue.Body = new theResearchSite.ValidationService.isURLRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.isURLResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).isURL(inValue);
            return retVal.Body.isURLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.isURLResponse> theResearchSite.ValidationService.ValidationSoap.isURLAsync(theResearchSite.ValidationService.isURLRequest request) {
            return base.Channel.isURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.isURLResponse> isURLAsync(string str) {
            theResearchSite.ValidationService.isURLRequest inValue = new theResearchSite.ValidationService.isURLRequest();
            inValue.Body = new theResearchSite.ValidationService.isURLRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).isURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.ValidationService.is5NumbersResponse theResearchSite.ValidationService.ValidationSoap.is5Numbers(theResearchSite.ValidationService.is5NumbersRequest request) {
            return base.Channel.is5Numbers(request);
        }
        
        public bool is5Numbers(string str) {
            theResearchSite.ValidationService.is5NumbersRequest inValue = new theResearchSite.ValidationService.is5NumbersRequest();
            inValue.Body = new theResearchSite.ValidationService.is5NumbersRequestBody();
            inValue.Body.str = str;
            theResearchSite.ValidationService.is5NumbersResponse retVal = ((theResearchSite.ValidationService.ValidationSoap)(this)).is5Numbers(inValue);
            return retVal.Body.is5NumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.ValidationService.is5NumbersResponse> theResearchSite.ValidationService.ValidationSoap.is5NumbersAsync(theResearchSite.ValidationService.is5NumbersRequest request) {
            return base.Channel.is5NumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.ValidationService.is5NumbersResponse> is5NumbersAsync(string str) {
            theResearchSite.ValidationService.is5NumbersRequest inValue = new theResearchSite.ValidationService.is5NumbersRequest();
            inValue.Body = new theResearchSite.ValidationService.is5NumbersRequestBody();
            inValue.Body.str = str;
            return ((theResearchSite.ValidationService.ValidationSoap)(this)).is5NumbersAsync(inValue);
        }
    }
}
