//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfTheResearch.HumanService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch", ItemName="User")]
    [System.SerializableAttribute()]
    public class UserList : System.Collections.Generic.List<wpfTheResearch.HumanService.User> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class User : wpfTheResearch.HumanService.Human {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((this.IdUserField.Equals(value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.HumanService.AuthLevel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.HumanService.Human))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.HumanService.Worker))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.HumanService.User))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthLevel", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class AuthLevel : wpfTheResearch.HumanService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Human", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.HumanService.Worker))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.HumanService.User))]
    public partial class Human : wpfTheResearch.HumanService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wpfTheResearch.HumanService.AuthLevel authLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime joinDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wpfTheResearch.HumanService.AuthLevel authLevel {
            get {
                return this.authLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.authLevelField, value) != true)) {
                    this.authLevelField = value;
                    this.RaisePropertyChanged("authLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime joinDate {
            get {
                return this.joinDateField;
            }
            set {
                if ((this.joinDateField.Equals(value) != true)) {
                    this.joinDateField = value;
                    this.RaisePropertyChanged("joinDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class Worker : wpfTheResearch.HumanService.Human {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double salaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double salary {
            get {
                return this.salaryField;
            }
            set {
                if ((this.salaryField.Equals(value) != true)) {
                    this.salaryField = value;
                    this.RaisePropertyChanged("salary");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultHumans", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class ServiceFaultHumans : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="WorkerList", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch", ItemName="Human")]
    [System.SerializableAttribute()]
    public class WorkerList : System.Collections.Generic.List<wpfTheResearch.HumanService.Human> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.humanType", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    public enum EnumshumanType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        user = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        worker = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        all = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HumanService.IHuman")]
    public interface IHuman {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/selectAllUsers", ReplyAction="http://tempuri.org/IHuman/selectAllUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(wpfTheResearch.HumanService.ServiceFaultHumans), Action="http://tempuri.org/IHuman/selectAllUsersServiceFaultHumansFault", Name="ServiceFaultHumans", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
        wpfTheResearch.HumanService.UserList selectAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/selectAllUsers", ReplyAction="http://tempuri.org/IHuman/selectAllUsersResponse")]
        System.Threading.Tasks.Task<wpfTheResearch.HumanService.UserList> selectAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/selectAllWorkers", ReplyAction="http://tempuri.org/IHuman/selectAllWorkersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(wpfTheResearch.HumanService.ServiceFaultHumans), Action="http://tempuri.org/IHuman/selectAllWorkersServiceFaultHumansFault", Name="ServiceFaultHumans", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
        wpfTheResearch.HumanService.WorkerList selectAllWorkers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/selectAllWorkers", ReplyAction="http://tempuri.org/IHuman/selectAllWorkersResponse")]
        System.Threading.Tasks.Task<wpfTheResearch.HumanService.WorkerList> selectAllWorkersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/Add", ReplyAction="http://tempuri.org/IHuman/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(wpfTheResearch.HumanService.ServiceFaultHumans), Action="http://tempuri.org/IHuman/AddServiceFaultHumansFault", Name="ServiceFaultHumans", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
        int Add(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/Add", ReplyAction="http://tempuri.org/IHuman/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/Update", ReplyAction="http://tempuri.org/IHuman/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(wpfTheResearch.HumanService.ServiceFaultHumans), Action="http://tempuri.org/IHuman/UpdateServiceFaultHumansFault", Name="ServiceFaultHumans", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
        int Update(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/Update", ReplyAction="http://tempuri.org/IHuman/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/Remove", ReplyAction="http://tempuri.org/IHuman/RemoveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(wpfTheResearch.HumanService.ServiceFaultHumans), Action="http://tempuri.org/IHuman/RemoveServiceFaultHumansFault", Name="ServiceFaultHumans", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
        int Remove(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHuman/Remove", ReplyAction="http://tempuri.org/IHuman/RemoveResponse")]
        System.Threading.Tasks.Task<int> RemoveAsync(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHumanChannel : wpfTheResearch.HumanService.IHuman, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HumanClient : System.ServiceModel.ClientBase<wpfTheResearch.HumanService.IHuman>, wpfTheResearch.HumanService.IHuman {
        
        public HumanClient() {
        }
        
        public HumanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HumanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wpfTheResearch.HumanService.UserList selectAllUsers() {
            return base.Channel.selectAllUsers();
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.HumanService.UserList> selectAllUsersAsync() {
            return base.Channel.selectAllUsersAsync();
        }
        
        public wpfTheResearch.HumanService.WorkerList selectAllWorkers() {
            return base.Channel.selectAllWorkers();
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.HumanService.WorkerList> selectAllWorkersAsync() {
            return base.Channel.selectAllWorkersAsync();
        }
        
        public int Add(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human) {
            return base.Channel.Add(humanType, human);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human) {
            return base.Channel.AddAsync(humanType, human);
        }
        
        public int Update(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human) {
            return base.Channel.Update(humanType, human);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human) {
            return base.Channel.UpdateAsync(humanType, human);
        }
        
        public int Remove(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human) {
            return base.Channel.Remove(humanType, human);
        }
        
        public System.Threading.Tasks.Task<int> RemoveAsync(wpfTheResearch.HumanService.EnumshumanType humanType, wpfTheResearch.HumanService.Human human) {
            return base.Channel.RemoveAsync(humanType, human);
        }
    }
}
