//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfTheResearch.NewsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="NewsList", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch", ItemName="News")]
    [System.SerializableAttribute()]
    public class NewsList : System.Collections.Generic.List<wpfTheResearch.NewsService.News> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class News : wpfTheResearch.NewsService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wpfTheResearch.NewsService.AuthLevel AuthLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wpfTheResearch.NewsService.Category categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateTimePublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string headLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secondaryTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int viewsCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wpfTheResearch.NewsService.AuthLevel AuthLevel {
            get {
                return this.AuthLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthLevelField, value) != true)) {
                    this.AuthLevelField = value;
                    this.RaisePropertyChanged("AuthLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wpfTheResearch.NewsService.Category category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateTimePublished {
            get {
                return this.dateTimePublishedField;
            }
            set {
                if ((this.dateTimePublishedField.Equals(value) != true)) {
                    this.dateTimePublishedField = value;
                    this.RaisePropertyChanged("dateTimePublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string headLine {
            get {
                return this.headLineField;
            }
            set {
                if ((object.ReferenceEquals(this.headLineField, value) != true)) {
                    this.headLineField = value;
                    this.RaisePropertyChanged("headLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagePath {
            get {
                return this.imagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.imagePathField, value) != true)) {
                    this.imagePathField = value;
                    this.RaisePropertyChanged("imagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string secondaryTitle {
            get {
                return this.secondaryTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.secondaryTitleField, value) != true)) {
                    this.secondaryTitleField = value;
                    this.RaisePropertyChanged("secondaryTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int viewsCount {
            get {
                return this.viewsCountField;
            }
            set {
                if ((this.viewsCountField.Equals(value) != true)) {
                    this.viewsCountField = value;
                    this.RaisePropertyChanged("viewsCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.NewsService.AuthLevel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.NewsService.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wpfTheResearch.NewsService.News))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthLevel", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class AuthLevel : wpfTheResearch.NewsService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class Category : wpfTheResearch.NewsService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsService.INews")]
    public interface INews {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/selectAll", ReplyAction="http://tempuri.org/INews/selectAllResponse")]
        wpfTheResearch.NewsService.NewsList selectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/selectAll", ReplyAction="http://tempuri.org/INews/selectAllResponse")]
        System.Threading.Tasks.Task<wpfTheResearch.NewsService.NewsList> selectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/Add", ReplyAction="http://tempuri.org/INews/AddResponse")]
        int Add(wpfTheResearch.NewsService.News news);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/Add", ReplyAction="http://tempuri.org/INews/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(wpfTheResearch.NewsService.News news);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/Update", ReplyAction="http://tempuri.org/INews/UpdateResponse")]
        int Update(wpfTheResearch.NewsService.News news);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/Update", ReplyAction="http://tempuri.org/INews/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(wpfTheResearch.NewsService.News news);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsChannel : wpfTheResearch.NewsService.INews, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsClient : System.ServiceModel.ClientBase<wpfTheResearch.NewsService.INews>, wpfTheResearch.NewsService.INews {
        
        public NewsClient() {
        }
        
        public NewsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wpfTheResearch.NewsService.NewsList selectAll() {
            return base.Channel.selectAll();
        }
        
        public System.Threading.Tasks.Task<wpfTheResearch.NewsService.NewsList> selectAllAsync() {
            return base.Channel.selectAllAsync();
        }
        
        public int Add(wpfTheResearch.NewsService.News news) {
            return base.Channel.Add(news);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(wpfTheResearch.NewsService.News news) {
            return base.Channel.AddAsync(news);
        }
        
        public int Update(wpfTheResearch.NewsService.News news) {
            return base.Channel.Update(news);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(wpfTheResearch.NewsService.News news) {
            return base.Channel.UpdateAsync(news);
        }
    }
}
