//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theResearchSite.NewsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="NewsList", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch", ItemName="News")]
    [System.SerializableAttribute()]
    public class NewsList : System.Collections.Generic.List<theResearchSite.NewsService.News> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class News : theResearchSite.NewsService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private theResearchSite.NewsService.AuthLevel AuthLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateTimePublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string headLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secondaryTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private theResearchSite.NewsService.UserList stuffField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public theResearchSite.NewsService.AuthLevel AuthLevel {
            get {
                return this.AuthLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthLevelField, value) != true)) {
                    this.AuthLevelField = value;
                    this.RaisePropertyChanged("AuthLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateTimePublished {
            get {
                return this.dateTimePublishedField;
            }
            set {
                if ((this.dateTimePublishedField.Equals(value) != true)) {
                    this.dateTimePublishedField = value;
                    this.RaisePropertyChanged("dateTimePublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string headLine {
            get {
                return this.headLineField;
            }
            set {
                if ((object.ReferenceEquals(this.headLineField, value) != true)) {
                    this.headLineField = value;
                    this.RaisePropertyChanged("headLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagePath {
            get {
                return this.imagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.imagePathField, value) != true)) {
                    this.imagePathField = value;
                    this.RaisePropertyChanged("imagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string secondaryTitle {
            get {
                return this.secondaryTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.secondaryTitleField, value) != true)) {
                    this.secondaryTitleField = value;
                    this.RaisePropertyChanged("secondaryTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public theResearchSite.NewsService.UserList stuff {
            get {
                return this.stuffField;
            }
            set {
                if ((object.ReferenceEquals(this.stuffField, value) != true)) {
                    this.stuffField = value;
                    this.RaisePropertyChanged("stuff");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(theResearchSite.NewsService.AuthLevel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(theResearchSite.NewsService.Human))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(theResearchSite.NewsService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(theResearchSite.NewsService.News))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthLevel", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class AuthLevel : theResearchSite.NewsService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Human", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(theResearchSite.NewsService.User))]
    public partial class Human : theResearchSite.NewsService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private theResearchSite.NewsService.AuthLevel authLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public theResearchSite.NewsService.AuthLevel authLevel {
            get {
                return this.authLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.authLevelField, value) != true)) {
                    this.authLevelField = value;
                    this.RaisePropertyChanged("authLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                if ((this.birthDateField.Equals(value) != true)) {
                    this.birthDateField = value;
                    this.RaisePropertyChanged("birthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch")]
    [System.SerializableAttribute()]
    public partial class User : theResearchSite.NewsService.Human {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((this.IdUserField.Equals(value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/ModelTheResearch", ItemName="User")]
    [System.SerializableAttribute()]
    public class UserList : System.Collections.Generic.List<theResearchSite.NewsService.User> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsService.INews")]
    public interface INews {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/selectAll", ReplyAction="http://tempuri.org/INews/selectAllResponse")]
        theResearchSite.NewsService.NewsList selectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/selectAll", ReplyAction="http://tempuri.org/INews/selectAllResponse")]
        System.Threading.Tasks.Task<theResearchSite.NewsService.NewsList> selectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/Add", ReplyAction="http://tempuri.org/INews/AddResponse")]
        int Add(theResearchSite.NewsService.News news);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/Add", ReplyAction="http://tempuri.org/INews/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(theResearchSite.NewsService.News news);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/Update", ReplyAction="http://tempuri.org/INews/UpdateResponse")]
        int Update(theResearchSite.NewsService.News news);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INews/Update", ReplyAction="http://tempuri.org/INews/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(theResearchSite.NewsService.News news);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsChannel : theResearchSite.NewsService.INews, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsClient : System.ServiceModel.ClientBase<theResearchSite.NewsService.INews>, theResearchSite.NewsService.INews {
        
        public NewsClient() {
        }
        
        public NewsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public theResearchSite.NewsService.NewsList selectAll() {
            return base.Channel.selectAll();
        }
        
        public System.Threading.Tasks.Task<theResearchSite.NewsService.NewsList> selectAllAsync() {
            return base.Channel.selectAllAsync();
        }
        
        public int Add(theResearchSite.NewsService.News news) {
            return base.Channel.Add(news);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(theResearchSite.NewsService.News news) {
            return base.Channel.AddAsync(news);
        }
        
        public int Update(theResearchSite.NewsService.News news) {
            return base.Channel.Update(news);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(theResearchSite.NewsService.News news) {
            return base.Channel.UpdateAsync(news);
        }
    }
}
