//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theResearchSite.IdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IdService.IdToolsSoap")]
    public interface IdToolsSoap {
        
        // CODEGEN: Generating message contract since element name idNum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckIsraelIdNum", ReplyAction="*")]
        theResearchSite.IdService.CheckIsraelIdNumResponse CheckIsraelIdNum(theResearchSite.IdService.CheckIsraelIdNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckIsraelIdNum", ReplyAction="*")]
        System.Threading.Tasks.Task<theResearchSite.IdService.CheckIsraelIdNumResponse> CheckIsraelIdNumAsync(theResearchSite.IdService.CheckIsraelIdNumRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckIsraelIdNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckIsraelIdNum", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.IdService.CheckIsraelIdNumRequestBody Body;
        
        public CheckIsraelIdNumRequest() {
        }
        
        public CheckIsraelIdNumRequest(theResearchSite.IdService.CheckIsraelIdNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckIsraelIdNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idNum;
        
        public CheckIsraelIdNumRequestBody() {
        }
        
        public CheckIsraelIdNumRequestBody(string idNum) {
            this.idNum = idNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckIsraelIdNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckIsraelIdNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public theResearchSite.IdService.CheckIsraelIdNumResponseBody Body;
        
        public CheckIsraelIdNumResponse() {
        }
        
        public CheckIsraelIdNumResponse(theResearchSite.IdService.CheckIsraelIdNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckIsraelIdNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckIsraelIdNumResult;
        
        public CheckIsraelIdNumResponseBody() {
        }
        
        public CheckIsraelIdNumResponseBody(bool CheckIsraelIdNumResult) {
            this.CheckIsraelIdNumResult = CheckIsraelIdNumResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IdToolsSoapChannel : theResearchSite.IdService.IdToolsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdToolsSoapClient : System.ServiceModel.ClientBase<theResearchSite.IdService.IdToolsSoap>, theResearchSite.IdService.IdToolsSoap {
        
        public IdToolsSoapClient() {
        }
        
        public IdToolsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdToolsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdToolsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdToolsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        theResearchSite.IdService.CheckIsraelIdNumResponse theResearchSite.IdService.IdToolsSoap.CheckIsraelIdNum(theResearchSite.IdService.CheckIsraelIdNumRequest request) {
            return base.Channel.CheckIsraelIdNum(request);
        }
        
        public bool CheckIsraelIdNum(string idNum) {
            theResearchSite.IdService.CheckIsraelIdNumRequest inValue = new theResearchSite.IdService.CheckIsraelIdNumRequest();
            inValue.Body = new theResearchSite.IdService.CheckIsraelIdNumRequestBody();
            inValue.Body.idNum = idNum;
            theResearchSite.IdService.CheckIsraelIdNumResponse retVal = ((theResearchSite.IdService.IdToolsSoap)(this)).CheckIsraelIdNum(inValue);
            return retVal.Body.CheckIsraelIdNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<theResearchSite.IdService.CheckIsraelIdNumResponse> theResearchSite.IdService.IdToolsSoap.CheckIsraelIdNumAsync(theResearchSite.IdService.CheckIsraelIdNumRequest request) {
            return base.Channel.CheckIsraelIdNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<theResearchSite.IdService.CheckIsraelIdNumResponse> CheckIsraelIdNumAsync(string idNum) {
            theResearchSite.IdService.CheckIsraelIdNumRequest inValue = new theResearchSite.IdService.CheckIsraelIdNumRequest();
            inValue.Body = new theResearchSite.IdService.CheckIsraelIdNumRequestBody();
            inValue.Body.idNum = idNum;
            return ((theResearchSite.IdService.IdToolsSoap)(this)).CheckIsraelIdNumAsync(inValue);
        }
    }
}
